/* extracted from http://www.bottlecaps.de/rr/ui on Mon Jan 8, 2018, 11:40 (UTC+01)
 */
ExpressionTreeGrammar ::= ExpressionTree'.'Date'.'Fix'(''DateTimeValue'')'
(
'.'StartAt'(''StringValue'')'
 (
  '.'Duration'(''StringValue'')'
  (
  If'('Days')''.'ThenStartAt'(''StringValue'')'
   (
   |'.'In'('YearType')'('.'Every'(''Number'')''.'Year'.'Since'(''Year'')')?
   |'.'Every'(''Number'')''.'Year'.'Since'(''Year'')'
   )?
  |'.'In'(''YearType'')'('.'Every'(''Number'')''.'Year'.'Since'(''Year'')')?
  |'.'Every'(''Number'')''.'Year'.'Since'(''Year'')'
  )?
 |'.'In'(''YearType'')'('.'Every'(''Number'')''.'Year'.'Since'(''Year'')')?
 |'.'Every'(''Number'')''.'Year'.'Since'(''Year'')'
 )?
)?
Days ::= ('Monday'|'Tuesday'|'Wednesday'|'Thursday'|'Friday'|'Saturday'|'Sunday')
YearType ::= ('Even'|'Odd'|'Leap'|'NonLeap')