/* extracted from http://www.bottlecaps.de/rr/ui on Mon Jan 8, 2018, 11:40 (UTC+01)
 */
ExpressionTreeGrammar ::= ExpressionTree'.'Move'.'Fix'(''DateTimeValue'')''.'
  (
  If'('Days')''.'Then'.'(Previous|Next)'('Days')'
  |(If'('Days')''.'Then'.'(Previous|Next)'('Days')''.'Or'.')+
  )
Days ::= ('Monday'|'Tuesday'|'Wednesday'|'Thursday'|'Friday'|'Saturday'|'Sunday')