/* extracted from http://www.bottlecaps.de/rr/ui on Mon Jan 8, 2018, 11:40 (UTC+01)
 */
ExpressionTreeGrammar ::= ExpressionTree'.'Date'.'Orthodox'.'(Christianism|CustomDay'(''StringValue'')')(('.'Start'(''StringValue'')'('.'Duration'(''StringValue'')')?)?|('.'Duration'(''StringValue'')')?)?

Christianism ::=('CarnivalMonday'|'CarnivalTuesday'|'AshWednesday'|'PalmSunday'|'MaundyThursday'|'GoodFriday'|'HolySaturday'|'Easter'|'EasterMonday'|'AscensionDay'|'Pentecost'|'WhitMonday'|'CorpusChristi')